{
 "title": "OVMS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interface", "label": "interface", "query": "gRPC, REST" }
  ]
 },
 "panels": [
  {
   "title": "OVMS Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(ovms_request_time_us_count{interface=\"REST\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OVMS Inference Execution Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(ovms_inference_time_us_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OVMS Requests Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(ovms_requests_success{method=\"ModelInfer\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OVMS Requests Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(ovms_requests_fail[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Throughput (RPS)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ovms_requests_success{method=~\"ModelInfer|Predict\", interface=\"$interface\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Mean Latency (ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(rate(ovms_request_time_us_sum{interface=\"$interface\"}[1m])) / 1000) / sum(rate(ovms_request_time_us_count{interface=\"$interface\"}[1m])))",
     "legendFormat": "Mean Latency"
    }
   ]
  },
  {
   "title": "Latency Quantiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(ovms_request_time_us_bucket{interface=\"$interface\"}[1m]))) / 1000",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(ovms_request_time_us_bucket{interface=\"$interface\"}[1m]))) / 1000",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(ovms_request_time_us_bucket{interface=\"$interface\"}[1m]))) / 1000",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Currently Processed Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ovms_current_requests)", "legendFormat": "Active Requests" }
   ]
  },
  {
   "title": "Queue Wait Time",
   "type": "timeseries",
   "description": "Request waiting time in scheduling queue",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(ovms_wait_for_infer_req_time_us_sum[1m])) / 1000) / sum(rate(ovms_wait_for_infer_req_time_us_count[1m]))",
     "legendFormat": "Queue Wait Time"
    }
   ]
  }
 ]
}